In [33]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix

from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import SGDClassifier
from sklearn.svm import LinearSVC
from sklearn.preprocessing import MinMaxScaler


In [17]:
features=pd.read_csv('features.txt',delim_whitespace=True,header=None)
X=pd.read_csv('train/X_train.txt',delim_whitespace=True,header=None)
X.columns=features
X[:5]

(1, tBodyAcc-mean()-X)  (2, tBodyAcc-mean()-Y)  (3, tBodyAcc-mean()-Z)  \
0                0.288585               -0.020294               -0.132905   
1                0.278419               -0.016411               -0.123520   
2                0.279653               -0.019467               -0.113462   
3                0.279174               -0.026201               -0.123283   
4                0.276629               -0.016570               -0.115362   

   (4, tBodyAcc-std()-X)  (5, tBodyAcc-std()-Y)  (6, tBodyAcc-std()-Z)  \
0              -0.995279              -0.983111              -0.913526   
1              -0.998245              -0.975300              -0.960322   
2              -0.995380              -0.967187              -0.978944   
3              -0.996091              -0.983403              -0.990675   
4              -0.998139              -0.980817              -0.990482   

   (7, tBodyAcc-mad()-X)  (8, tBodyAcc-mad()-Y)  (9, tBodyAcc-mad()-Z)  \
0              -0.995112              -0.983185              -0.923527   
1              -0.998807              -0.974914              -0.957686   
2              -0.996520              -0.963668              -0.977469   
3              -0.997099              -0.982750              -0.989302   
4              -0.998321              -0.979672              -0.990441   

   (10, tBodyAcc-max()-X)             ...               \
0               -0.934724             ...                
1               -0.943068             ...                
2               -0.938692             ...                
3               -0.938692             ...                
4               -0.942469             ...                

   (552, fBodyBodyGyroJerkMag-meanFreq())  \
0                               -0.074323   
1                                0.158075   
2                                0.414503   
3                                0.404573   
4                                0.087753   

   (553, fBodyBodyGyroJerkMag-skewness())  \
0                               -0.298676   
1                               -0.595051   
2                               -0.390748   
3                               -0.117290   
4                               -0.351471   

   (554, fBodyBodyGyroJerkMag-kurtosis())  (555, angle(tBodyAccMean,gravity))  \
0                               -0.710304                           -0.112754   
1                               -0.861499                            0.053477   
2                               -0.760104                           -0.118559   
3                               -0.482845                           -0.036788   
4                               -0.699205                            0.123320   

   (556, angle(tBodyAccJerkMean),gravityMean))  \
0                                     0.030400   
1                                    -0.007435   
2                                     0.177899   
3                                    -0.012892   
4                                     0.122542   

   (557, angle(tBodyGyroMean,gravityMean))  \
0                                -0.464761   
1                                -0.732626   
2                                 0.100699   
3                                 0.640011   
4                                 0.693578   

   (558, angle(tBodyGyroJerkMean,gravityMean))  (559, angle(X,gravityMean))  \
0                                    -0.018446                    -0.841247   
1                                     0.703511                    -0.844788   
2                                     0.808529                    -0.848933   
3                                    -0.485366                    -0.848649   
4                                    -0.615971                    -0.847865   

   (560, angle(Y,gravityMean))  (561, angle(Z,gravityMean))  
0                     0.179941                    -0.058627  
1                     0.180289                    -0.054317  
2                     0.180637   

In [18]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7352 entries, 0 to 7351
Columns: 561 entries, (1, tBodyAcc-mean()-X) to (561, angle(Z,gravityMean))
dtypes: float64(561)
memory usage: 31.5 MB


In [19]:
y=pd.read_csv('train/y_train.txt',delim_whitespace=True,header=None)
y[:5]

0
0  5
1  5
2  5
3  5
4  5

In [21]:
X_train,X_test,y_train,y_test=train_test_split(X,y)

In [29]:
lr=LogisticRegression()
lr.fit(X_train,y_train)
print('train score: {}'.format(lr.score(X_train,y_train)))
print('test score: {}'.format(lr.score(X_test,y_test)))
print(confusion_matrix(y_test,lr.predict(X_test)))

/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


train score: 0.9922016684802322
test score: 0.9771490750816104
[[299   1   0   0   0   0]
 [  0 265   0   0   0   0]
 [  0   0 258   0   0   0]
 [  0   1   0 311  17   0]
 [  0   0   0  23 309   0]
 [  0   0   0   0   0 354]]


In [31]:
SGD=SGDClassifier()
SGD.fit(X_train,y_train)
print('train score: {}'.format(SGD.score(X_train,y_train)))
print('test score: {}'.format(SGD.score(X_test,y_test)))
print(confusion_matrix(y_test,SGD.predict(X_test)))

train score: 0.9733405875952121
test score: 0.9640914036996736
[[299   0   1   0   0   0]
 [  6 252   4   2   1   0]
 [  0   0 258   0   0   0]
 [  0   1   0 297  30   1]
 [  0   0   0  20 312   0]
 [  0   0   0   0   0 354]]


/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [34]:
SVC=LinearSVC()
SVC.fit(X_train,y_train)
print('train score: {}'.format(SVC.score(X_train,y_train)))
print('test score: {}'.format(SVC.score(X_test,y_test)))
print(confusion_matrix(y_test,SVC.predict(X_test)))

/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


train score: 0.9970982952484585
test score: 0.9804134929270947
[[299   1   0   0   0   0]
 [  0 265   0   0   0   0]
 [  0   0 258   0   0   0]
 [  0   1   0 314  14   0]
 [  0   0   0  20 312   0]
 [  0   0   0   0   0 354]]


In [35]:
scaler=MinMaxScaler()
X_scaled=scaler.fit_transform(X)
Xs_train,Xs_test,ys_train,ys_test=train_test_split(X_scaled,y)

In [36]:
SVC=LinearSVC()
SVC.fit(Xs_train,ys_train)
print('train score: {}'.format(SVC.score(Xs_train,ys_train)))
print('test score: {}'.format(SVC.score(Xs_test,ys_test)))
print(confusion_matrix(ys_test,SVC.predict(Xs_test)))

/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


train score: 0.9938338774029742
test score: 0.984766050054407
[[287   0   0   0   0   0]
 [  0 267   0   0   0   0]
 [  0   0 246   0   0   0]
 [  0   0   0 321  10   1]
 [  0   0   0  17 319   0]
 [  0   0   0   0   0 370]]
