In [1]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.datasets import make_circles

import mglearn
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split

X,y=make_circles(noise=0.25,factor=0.5,random_state=1)

y_named=np.array(['blue','red'])[y]

X_train, X_test, y_train_named, y_test_named, y_train,y_test=train_test_split(X,y_named,y,random_state=0)

gbrt=GradientBoostingClassifier(random_state=0)
gbrt.fit(X_train,y_train_named)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              presort='auto', random_state=0, subsample=1.0, verbose=0,
              warm_start=False)

In [2]:
#Decision Function - binary classification

print('X test shape: {}'.format(X_test.shape))
print('Decision function shape: {}'.format(gbrt.decision_function(X_test).shape))

X test shape: (25, 2)
Decision function shape: (25,)


In [3]:
print('decision function: {}'.format(gbrt.decision_function(X_test)[:6]))

decision function: [ 4.13592629 -1.7016989  -3.95106099 -3.62599351  4.28986668  3.66166106]


In [6]:
print('threshold decision function:\n {}'.format(gbrt.decision_function(X_test)>0))
print('predicitons: \n {}'.format(gbrt.predict(X_test)))

threshold decision function:
 [ True False False False  True  True False  True  True  True False  True
  True False  True False False False  True  True  True  True  True False
 False]
predicitons: 
 ['red' 'blue' 'blue' 'blue' 'red' 'red' 'blue' 'red' 'red' 'red' 'blue'
 'red' 'red' 'blue' 'red' 'blue' 'blue' 'blue' 'red' 'red' 'red' 'red'
 'red' 'blue' 'blue']


In [7]:
greater_zero=(gbrt.decision_function(X_test)>0).astype(int)
pred=gbrt.classes_[greater_zero]
print('pred equal to predictions: {}'.format(np.all(pred==gbrt.predict(X_test))))

pred equal to predictions: True


In [15]:
decision_function=gbrt.decision_function(X_test)
print('dec func min: {} max: {}'.format(np.min(decision_function),np.max(decision_function)))

dec func min: -7.69097177301218 max: 4.289866676868515


In [9]:


#predicting probabilities

print("shape of probabilities: {}".format(gbrt.predict_proba(X_test).shape))

shape of probabilities: (25, 2)


In [25]:
#first column is probability of first class, second colum is prob of second class

print('predicted probabilities: \n {}'.format(gbrt.predict_proba(X_test)))

predicted probabilities: 
 [[  1.57362600e-02   9.84263740e-01]
 [  8.45756491e-01   1.54243509e-01]
 [  9.81128693e-01   1.88713075e-02]
 [  9.74067751e-01   2.59322495e-02]
 [  1.35214179e-02   9.86478582e-01]
 [  2.50463685e-02   9.74953631e-01]
 [  9.99543275e-01   4.56725227e-04]
 [  1.61426459e-02   9.83857354e-01]
 [  2.48330011e-01   7.51669989e-01]
 [  3.20518856e-02   9.67948114e-01]
 [  9.98441742e-01   1.55825797e-03]
 [  1.35214179e-02   9.86478582e-01]
 [  1.98099196e-02   9.80190080e-01]
 [  7.68580268e-01   2.31419732e-01]
 [  2.50463685e-02   9.74953631e-01]
 [  9.84817488e-01   1.51825121e-02]
 [  7.73836115e-01   2.26163885e-01]
 [  9.80463918e-01   1.95360817e-02]
 [  1.73607853e-02   9.82639215e-01]
 [  1.61426459e-02   9.83857354e-01]
 [  1.61426459e-02   9.83857354e-01]
 [  3.41393690e-01   6.58606310e-01]
 [  6.30759354e-02   9.36924065e-01]
 [  9.34424780e-01   6.55752202e-02]
 [  8.66199569e-01   1.33800431e-01]]


In [26]:
from sklearn.datasets import load_iris

iris=load_iris()
X_train,X_test,y_train,y_test=train_test_split(iris.data,iris.target,random_state=42)

gbrt=GradientBoostingClassifier(learning_rate=0.01, random_state=0)
gbrt.fit(X_train,y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.01, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              presort='auto', random_state=0, subsample=1.0, verbose=0,
              warm_start=False)

In [27]:
print("decision function shape: \n {}".format(gbrt.decision_function(X_test).shape))
print("decision function: \n {}".format(gbrt.decision_function(X_test)))

decision function shape: 
 (38, 3)
decision function: 
 [[-0.52931069  1.46560359 -0.50448467]
 [ 1.51154215 -0.49561142 -0.50310736]
 [-0.52379401 -0.4676268   1.51953786]
 [-0.52931069  1.46560359 -0.50448467]
 [-0.53107259  1.28190451  0.21510024]
 [ 1.51154215 -0.49561142 -0.50310736]
 [-0.52931069  1.46560359 -0.50448467]
 [-0.53043817 -0.4676268   1.51953786]
 [-0.52931069  1.46560359 -0.50448467]
 [-0.52931069  1.46560359 -0.50448467]
 [-0.53043817 -0.4676268   1.50129926]
 [ 1.51154215 -0.49561142 -0.50310736]
 [ 1.51154215 -0.49561142 -0.50310736]
 [ 1.51154215 -0.49561142 -0.50310736]
 [ 1.51154215 -0.49561142 -0.50310736]
 [-0.52931069  1.46560359 -0.50448467]
 [-0.52419721 -0.4676268   1.51953786]
 [-0.52931069  1.46560359 -0.50448467]
 [-0.52931069  1.46560359 -0.50448467]
 [-0.52419721 -0.4676268   1.51953786]
 [ 1.51154215 -0.49561142 -0.50310736]
 [-0.53107259 -0.45541112  1.46576456]
 [ 1.51154215 -0.49561142 -0.50310736]
 [-0.52419721 -0.4676268   1.51953786]
 [-0.524

In [28]:
print("predict probabilities: \n {}".format(gbrt.predict_proba(X_test)))

predict probabilities: 
 [[ 0.10664722  0.7840248   0.10932798]
 [ 0.78880668  0.10599243  0.10520089]
 [ 0.10231173  0.10822274  0.78946553]
 [ 0.10664722  0.7840248   0.10932798]
 [ 0.10825347  0.66344934  0.22829719]
 [ 0.78880668  0.10599243  0.10520089]
 [ 0.10664722  0.7840248   0.10932798]
 [ 0.10170311  0.10829611  0.79000078]
 [ 0.10664722  0.7840248   0.10932798]
 [ 0.10664722  0.7840248   0.10932798]
 [ 0.10317625  0.10986475  0.786959  ]
 [ 0.78880668  0.10599243  0.10520089]
 [ 0.78880668  0.10599243  0.10520089]
 [ 0.78880668  0.10599243  0.10520089]
 [ 0.78880668  0.10599243  0.10520089]
 [ 0.10664722  0.7840248   0.10932798]
 [ 0.1022747   0.1082272   0.78949809]
 [ 0.10664722  0.7840248   0.10932798]
 [ 0.10664722  0.7840248   0.10932798]
 [ 0.1022747   0.1082272   0.78949809]
 [ 0.78880668  0.10599243  0.10520089]
 [ 0.10588375  0.11420593  0.77991032]
 [ 0.78880668  0.10599243  0.10520089]
 [ 0.1022747   0.1082272   0.78949809]
 [ 0.10375517  0.10979383  0.786451  ]
