In [11]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.svm import SVC
from sklearn.metrics import roc_auc_score

from sklearn.datasets import load_digits
digits=load_digits()

import mglearn
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

print('default scoring: \n {}'.format(cross_val_score(SVC(),digits.data,digits.target==9)))
print('explicit accuracy scoring: \n {}'.format(cross_val_score(SVC(),digits.data,digits.target==9,scoring='accuracy')))
print('AUC scoring: \n {}'.format(cross_val_score(SVC(),digits.data,digits.target==9,scoring='roc_auc')))


default scoring: 
 [ 0.89983306  0.89983306  0.89983306]
explicit accuracy scoring: 
 [ 0.89983306  0.89983306  0.89983306]
AUC scoring: 
 [ 0.99372294  0.98957947  0.99594929]


In [17]:
X_train,X_test,y_train,y_test=train_test_split(digits.data,digits.target==9,random_state=0)

param_grid={'gamma':[0.0001,0.01,0.1,1,10]}
grid=GridSearchCV(SVC(),param_grid=param_grid)
grid.fit(X_train,y_train)

print('grid search with accuracy')
print('grid search best params: {}'.format(grid.best_params_))
print('best cross val score: {}'.format(grid.best_score_))
print('test AUC score: {}'.format(roc_auc_score(y_test,grid.decision_function(X_test))))
print('test set accuracy: {}'.format(grid.score(X_test,y_test)))

grid search with accuracy
grid search best params: {'gamma': 0.0001}
best cross val score: 0.9703043801039347
test AUC score: 0.9919222849902327
test set accuracy: 0.9733333333333334


In [18]:
grid=GridSearchCV(SVC(),param_grid=param_grid,scoring='roc_auc')
grid.fit(X_train,y_train)

print('grid search with AUC')
print('grid search best params: {}'.format(grid.best_params_))
print('best cross val score: {}'.format(grid.best_score_))
print('test AUC score: {}'.format(roc_auc_score(y_test,grid.decision_function(X_test))))
print('test set accuracy: {}'.format(grid.score(X_test,y_test)))

grid search with AUC
grid search best params: {'gamma': 0.01}
best cross val score: 0.997467845027512
test AUC score: 0.999524840293543
test set accuracy: 0.999524840293543


In [20]:
from sklearn.metrics import SCORERS

print(sorted(SCORERS.keys()))

['accuracy', 'adjusted_mutual_info_score', 'adjusted_rand_score', 'average_precision', 'completeness_score', 'explained_variance', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'fowlkes_mallows_score', 'homogeneity_score', 'log_loss', 'mean_absolute_error', 'mean_squared_error', 'median_absolute_error', 'mutual_info_score', 'neg_log_loss', 'neg_mean_absolute_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_median_absolute_error', 'normalized_mutual_info_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'r2', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'roc_auc', 'v_measure_score']
