In [114]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sys, csv, os

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix

In [119]:
data=pd.read_csv('iris.data', names=['sepal_len','sepal_wid','petal_len','petal_wid','class'])
data[:5]

sepal_len  sepal_wid  petal_len  petal_wid        class
0        5.1        3.5        1.4        0.2  Iris-setosa
1        4.9        3.0        1.4        0.2  Iris-setosa
2        4.7        3.2        1.3        0.2  Iris-setosa
3        4.6        3.1        1.5        0.2  Iris-setosa
4        5.0        3.6        1.4        0.2  Iris-setosa

In [23]:
data.columns

Index(['sepal_len', 'sepal_wid', 'petal_len', 'petal_wid', 'class'], dtype='object')

In [39]:
y=list(data['class'])
y[:5]

['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa']

In [65]:
X=np.array(data[['sepal_len','sepal_wid','petal_len','petal_wid']])

In [66]:
X[:5]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2]])

In [68]:
X_train,X_test,y_train,y_test=train_test_split(X,y)

In [93]:
clf=KNeighborsClassifier(n_neighbors=3)

In [117]:
clf.fit(X_train,y_train)
print(clf.score(X_train,y_train))
print(clf.score(X_test,y_test))

pred_knn=clf.predict(X_test)
confusion=confusion_matrix(y_test,pred_knn)
print(confusion)

0.964285714286
0.947368421053
[[14  0  0]
 [ 0  8  0]
 [ 0  2 14]]


In [116]:
svm=LinearSVC().fit(X_train,y_train)
print(svm.score(X_train,y_train))
print(svm.score(X_test,y_test))

pred_linSVC=svm.predict(X_test)
confusion=confusion_matrix(y_test,pred_linSVC)
print(confusion)

0.964285714286
0.947368421053
[[14  0  0]
 [ 0  8  0]
 [ 0  2 14]]


In [97]:
param_grid=[{'kernel':['rbf'],
            'C':[0.001,0.01,0.1,1,10,100], 'gamma':[0.001,0.01,0.1,1,10,100]},
           {'kernel':['linear'],
           'C':[0.001,0.01,0.1,1,10,100]}]

In [103]:
grid_search=GridSearchCV(SVC(),param_grid,cv=5)
grid_search.fit(X_train,y_train)

GridSearchCV(cv=5, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid=[{'kernel': ['rbf'], 'C': [0.001, 0.01, 0.1, 1, 10, 100], 'gamma': [0.001, 0.01, 0.1, 1, 10, 100]}, {'kernel': ['linear'], 'C': [0.001, 0.01, 0.1, 1, 10, 100]}],
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [106]:
print(grid_search.best_params_)
print(grid_search.best_score_)

{'C': 100, 'kernel': 'linear'}
0.982142857143


In [115]:
svm_opt=SVC(C=100,kernel='linear').fit(X_train,y_train)
print(svm.score(X_train,y_train))
print(svm.score(X_test,y_test))

pred_SVC=svm_opt.predict(X_test)
confusion=confusion_matrix(y_test,pred_SVC)
print(confusion)

0.964285714286
0.947368421053
[[14  0  0]
 [ 0  8  0]
 [ 0  1 15]]


38