In [4]:
import numpy as np

my_arr=np.arange(100000)
my_list=list(range(100000))

%time for _ in range(10): my_arr2=my_arr*2
%time for _ in range(10): my_list2=[x*2 for x in my_list]

CPU times: user 3.35 ms, sys: 0 ns, total: 3.35 ms
Wall time: 2.13 ms
CPU times: user 79.6 ms, sys: 3.98 ms, total: 83.6 ms
Wall time: 83.2 ms


In [3]:
#wow, much faster

In [5]:
data=np.random.randn(2,3)
data

array([[-2.84172116,  0.7602459 , -0.40983876],
       [ 0.58350179, -0.55840566, -0.7761544 ]])

In [6]:
data*10

array([[-28.41721157,   7.60245898,  -4.09838762],
       [  5.83501787,  -5.58405663,  -7.76154398]])

In [7]:
data+data

array([[-5.68344231,  1.5204918 , -0.81967752],
       [ 1.16700357, -1.11681133, -1.5523088 ]])

In [8]:
data.shape

(2, 3)

In [9]:
data.dtype

dtype('float64')

In [26]:
data1=[2,5,3,6,7.4,2]
arr1=np.array(data1)
arr1

array([ 2. ,  5. ,  3. ,  6. ,  7.4,  2. ])

In [27]:
data2=[2,6,4,1,4,7]
data3=[data1,data2]
data3

[[2, 5, 3, 6, 7.4, 2], [2, 6, 4, 1, 4, 7]]

In [29]:
arr2=np.array(data3)
arr2

array([[ 2. ,  5. ,  3. ,  6. ,  7.4,  2. ],
       [ 2. ,  6. ,  4. ,  1. ,  4. ,  7. ]])

In [36]:
print(arr2.ndim, '\n',arr2.shape)

2 
 (2, 6)


In [37]:
arr1.dtype

dtype('float64')

In [38]:
arr2.dtype

dtype('float64')

In [40]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [42]:
np.zeros((10,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [43]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [45]:
np.ones_like(np.zeros((10,3)))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [48]:
numeric_string=np.array(['1.25','2.3','5.6'],dtype=np.string_)
numeric_string

array([b'1.25', b'2.3', b'5.6'],
      dtype='|S4')

In [49]:
numeric_string.astype(float)

array([ 1.25,  2.3 ,  5.6 ])

In [51]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [53]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [54]:
1/arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [55]:
arr**.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

In [56]:
arr2=np.array([[1,4,3],[3,5,6]])
arr2

array([[1, 4, 3],
       [3, 5, 6]])

In [60]:
arr2==arr

array([[ True, False,  True],
       [False,  True,  True]], dtype=bool)

In [61]:
arr2<arr

array([[False, False, False],
       [ True, False, False]], dtype=bool)

In [64]:
arr[1]

array([4, 5, 6])

In [65]:
arr[1,2]

6

In [66]:
arr[0,1]

2

In [75]:
arr[0,0:2]

array([1, 2])

In [76]:
arr[0]

array([1, 2, 3])

In [96]:
arr=np.arange(10)

In [97]:
arr_slice=arr[5:8]
arr_slice

array([5, 6, 7])

In [98]:
arr_slice[1]=12
arr_slice

array([ 5, 12,  7])

In [99]:
arr

array([ 0,  1,  2,  3,  4,  5, 12,  7,  8,  9])

In [104]:
names=np.array(['bob','john','alan','bob','bingo','joe'])
data=np.random.randn(len(names),4)
data

array([[-1.23810955, -0.0844292 ,  0.66013862,  0.41601995],
       [ 1.97421008, -0.32693612,  0.09967236, -0.11175835],
       [-0.11348325,  1.56819766, -0.11122272,  1.8111306 ],
       [-0.12321915, -0.00270672, -0.26368424,  2.38969469],
       [-1.41875388, -1.78475266, -0.21264048,  1.20430204],
       [ 0.46807356,  0.10899577,  0.39033037, -0.45132725]])

In [105]:
names=='bob'

array([ True, False, False,  True, False, False], dtype=bool)

In [106]:
data[names=='bob']

array([[-1.23810955, -0.0844292 ,  0.66013862,  0.41601995],
       [-0.12321915, -0.00270672, -0.26368424,  2.38969469]])

In [107]:
data[names=='bob',:2]

array([[-1.23810955, -0.0844292 ],
       [-0.12321915, -0.00270672]])

In [108]:
data[data<0]

array([-1.23810955, -0.0844292 , -0.32693612, -0.11175835, -0.11348325,
       -0.11122272, -0.12321915, -0.00270672, -0.26368424, -1.41875388,
       -1.78475266, -0.21264048, -0.45132725])

In [113]:
for i in range(len(arr)):
    arr[i]=i
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
arr=np.empty((8,4))
for i in range(8):
    arr[i]=i
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [126]:
np.arange(32).reshape((8,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])