In [1]:
import numpy as np

In [2]:
arr=np.arange(10)

In [3]:
 np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [4]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [5]:
x=np.random.randn(8)
y=np.random.randn(8)
np.maximum(x,y)

array([-0.14487049,  0.25330092, -0.66559787, -0.05474495,  0.6132257 ,
        2.1782249 ,  1.04664107, -0.32547235])

In [8]:
arr=np.random.randn(10)
arr

array([-0.24007148, -1.37600264, -2.98459066, -1.93019411,  0.1072961 ,
        0.88534816, -0.07458681, -1.47136116,  1.01550061,  0.04819618])

In [9]:
remainder,whole=np.modf(arr)

In [10]:
remainder

array([-0.24007148, -0.37600264, -0.98459066, -0.93019411,  0.1072961 ,
        0.88534816, -0.07458681, -0.47136116,  0.01550061,  0.04819618])

In [11]:
whole

array([-0., -1., -2., -1.,  0.,  0., -0., -1.,  1.,  0.])

In [12]:
whole.dtype

dtype('float64')

In [13]:
remainder.dtype

dtype('float64')