In [1]:
import numpy as np

In [4]:
arr=np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [6]:
arr.T #transpose

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [8]:
arr2=np.random.randn(6,3)
arr2

array([[-0.57350427, -0.30504206,  0.39650998],
       [-2.15829717,  0.26583811,  0.11848592],
       [ 2.20243732,  1.37248632,  0.50184367],
       [ 0.38322682,  0.52611052, -0.49402625],
       [-0.31309032,  0.00937567, -1.09961463],
       [-0.47317422,  0.87971457,  0.45863466]])

In [10]:
np.dot(arr2.T,arr2)

array([[ 10.30666614,   2.40642636,   0.56009172],
       [  2.40642636,   3.09821716,   0.73256498],
       [  0.56009172,   0.73256498,   2.08666616]])

In [13]:
arr=np.arange(16).reshape(2,2,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [14]:
arr.T

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [17]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [18]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])